fix script path

diff --git a/src/deploy-k8s/jobs/deploy.yml b/src/deploy-k8s/jobs/deploy.yml
--- a/src/deploy-k8s/jobs/deploy.yml
+++ b/src/deploy-k8s/jobs/deploy.yml
@@ -20,10 +20,10 @@ steps:
   - run:
       name: "Deploy"
       command: |
-        if [[ ! -x /kube-ci/deploy.sh ]]; then
-          echo "/kube-ci/deploy.sh script not found or not executable." 1>&2
+        if [[ ! -x /kube-ci/scripts/deploy.sh ]]; then
+          echo "/kube-ci/scripts/deploy.sh script not found or not executable." 1>&2
           echo "Make sure the image on the passed executor contains this script." 1>&2
           exit -1
         fi
 
-        /kube-ci/deploy.sh -r '<< parameters.cluster-regions >>' -e '<< parameters.environment >>'
+        /kube-ci/scripts/deploy.sh -r '<< parameters.cluster-regions >>' -e '<< parameters.environment >>'
